[package]
name = "rls_rnplug"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.28", features = ["serialize"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
zip = "0.6"
